package com.wizinno.jas.application.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Application implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.patient_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.doctor_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private Long doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.status
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.createtime
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.id
     *
     * @return the value of application.id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.id
     *
     * @param id the value for application.id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.patient_id
     *
     * @return the value of application.patient_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.patient_id
     *
     * @param patientId the value for application.patient_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.doctor_id
     *
     * @return the value of application.doctor_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.doctor_id
     *
     * @param doctorId the value for application.doctor_id
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.status
     *
     * @return the value of application.status
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.status
     *
     * @param status the value for application.status
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.createtime
     *
     * @return the value of application.createtime
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.createtime
     *
     * @param createtime the value for application.createtime
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}