package com.wizinno.jas.operationLog.domain.model;

import java.io.Serializable;
import java.util.Date;

public class OperationLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.user_id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.user_name
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.ip_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.event
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.status_code
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.request_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String requestAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.reponse_content
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private String reponseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.createtime
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.user_id
     *
     * @return the value of operation_log.user_id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.user_id
     *
     * @param userId the value for operation_log.user_id
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.user_name
     *
     * @return the value of operation_log.user_name
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.user_name
     *
     * @param userName the value for operation_log.user_name
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.ip_address
     *
     * @return the value of operation_log.ip_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.ip_address
     *
     * @param ipAddress the value for operation_log.ip_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.event
     *
     * @return the value of operation_log.event
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.event
     *
     * @param event the value for operation_log.event
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.status_code
     *
     * @return the value of operation_log.status_code
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.status_code
     *
     * @param statusCode the value for operation_log.status_code
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.request_address
     *
     * @return the value of operation_log.request_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getRequestAddress() {
        return requestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.request_address
     *
     * @param requestAddress the value for operation_log.request_address
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setRequestAddress(String requestAddress) {
        this.requestAddress = requestAddress == null ? null : requestAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.reponse_content
     *
     * @return the value of operation_log.reponse_content
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public String getReponseContent() {
        return reponseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.reponse_content
     *
     * @param reponseContent the value for operation_log.reponse_content
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setReponseContent(String reponseContent) {
        this.reponseContent = reponseContent == null ? null : reponseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.createtime
     *
     * @return the value of operation_log.createtime
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.createtime
     *
     * @param createtime the value for operation_log.createtime
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}