package com.wizinno.jas.archival.domain;

import com.wizinno.jas.archival.domain.model.ClinicalData;
import java.util.List;

public interface ClinicalDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    int insert(ClinicalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    ClinicalData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    List<ClinicalData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    int updateByPrimaryKey(ClinicalData record);

    List<ClinicalData> getImgByMaId(Long maId);
}