package com.wizinno.jas.archival.domain;

import com.wizinno.jas.archival.domain.model.MedicalArchival;
import java.util.List;

public interface MedicalArchivalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    int insert(MedicalArchival record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    MedicalArchival selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    List<MedicalArchival> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    int updateByPrimaryKey(MedicalArchival record);

    Long last();

    List<MedicalArchival> getMArchivalByPatientId(Long id);
}