package com.wizinno.jas.exercise.domain.model;

import java.io.Serializable;
import java.util.Date;

public class ExerciseProcess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.patient_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.doctor_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Long doctorId;
    private Integer isComfirmed;
    private Date comfirmedTime;

    public Integer getIsComfirmed() {
        return isComfirmed;
    }

    public void setIsComfirmed(Integer isComfirmed) {
        this.isComfirmed = isComfirmed;
    }

    public Date getComfirmedTime() {
        return comfirmedTime;
    }

    public void setComfirmedTime(Date comfirmedTime) {
        this.comfirmedTime = comfirmedTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.arthro
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Integer arthro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.postion
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Integer postion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.direction
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Integer direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.start_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.end_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.note
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.create_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.update_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.sign
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Integer sign;

    private Integer report;

    private Integer record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.create_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_process.update_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public Integer getReport() {
        return report;
    }

    public void setReport(Integer report) {
        this.report = report;
    }

    public Integer getRecord() {
        return record;
    }

    public void setRecord(Integer record) {
        this.record = record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.id
     *
     * @return the value of exercise_process.id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.id
     *
     * @param id the value for exercise_process.id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.patient_id
     *
     * @return the value of exercise_process.patient_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.patient_id
     *
     * @param patientId the value for exercise_process.patient_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.doctor_id
     *
     * @return the value of exercise_process.doctor_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.doctor_id
     *
     * @param doctorId the value for exercise_process.doctor_id
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.arthro
     *
     * @return the value of exercise_process.arthro
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Integer getArthro() {
        return arthro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.arthro
     *
     * @param arthro the value for exercise_process.arthro
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setArthro(Integer arthro) {
        this.arthro = arthro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.postion
     *
     * @return the value of exercise_process.postion
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Integer getPostion() {
        return postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.postion
     *
     * @param postion the value for exercise_process.postion
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setPostion(Integer postion) {
        this.postion = postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.direction
     *
     * @return the value of exercise_process.direction
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.direction
     *
     * @param direction the value for exercise_process.direction
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.start_time
     *
     * @return the value of exercise_process.start_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.start_time
     *
     * @param startTime the value for exercise_process.start_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.end_time
     *
     * @return the value of exercise_process.end_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.end_time
     *
     * @param endTime the value for exercise_process.end_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.note
     *
     * @return the value of exercise_process.note
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.note
     *
     * @param note the value for exercise_process.note
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.create_by
     *
     * @return the value of exercise_process.create_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.create_by
     *
     * @param createBy the value for exercise_process.create_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.update_by
     *
     * @return the value of exercise_process.update_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.update_by
     *
     * @param updateBy the value for exercise_process.update_by
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.sign
     *
     * @return the value of exercise_process.sign
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Integer getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.sign
     *
     * @param sign the value for exercise_process.sign
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.create_time
     *
     * @return the value of exercise_process.create_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.create_time
     *
     * @param createTime the value for exercise_process.create_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_process.update_time
     *
     * @return the value of exercise_process.update_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_process.update_time
     *
     * @param updateTime the value for exercise_process.update_time
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}