package com.wizinno.jas.exercise.domain.model;

import com.wizinno.jas.exercise.service.dto.DataDto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class ExerciseRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.patient_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.device_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.arthro
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Integer arthro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.postion
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Integer postion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.direction
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Integer direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.geolocation
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private String geolocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.start_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.end_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.start_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private int startAngle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.end_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private int endAngle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.sr
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Integer sr;

    private String recordData;

    public String getRecordData() {
        return recordData;
    }

    public void setRecordData(String recordData) {
        this.recordData = recordData;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_record.create_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.id
     *
     * @return the value of exercise_record.id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.id
     *
     * @param id the value for exercise_record.id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.patient_id
     *
     * @return the value of exercise_record.patient_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.patient_id
     *
     * @param patientId the value for exercise_record.patient_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.device_id
     *
     * @return the value of exercise_record.device_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.device_id
     *
     * @param deviceId the value for exercise_record.device_id
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.arthro
     *
     * @return the value of exercise_record.arthro
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Integer getArthro() {
        return arthro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.arthro
     *
     * @param arthro the value for exercise_record.arthro
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setArthro(Integer arthro) {
        this.arthro = arthro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.postion
     *
     * @return the value of exercise_record.postion
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Integer getPostion() {
        return postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.postion
     *
     * @param postion the value for exercise_record.postion
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setPostion(Integer postion) {
        this.postion = postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.direction
     *
     * @return the value of exercise_record.direction
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.direction
     *
     * @param direction the value for exercise_record.direction
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.geolocation
     *
     * @return the value of exercise_record.geolocation
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public String getGeolocation() {
        return geolocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.geolocation
     *
     * @param geolocation the value for exercise_record.geolocation
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setGeolocation(String geolocation) {
        this.geolocation = geolocation == null ? null : geolocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.start_time
     *
     * @return the value of exercise_record.start_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.start_time
     *
     * @param startTime the value for exercise_record.start_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.end_time
     *
     * @return the value of exercise_record.end_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.end_time
     *
     * @param endTime the value for exercise_record.end_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.start_angle
     *
     * @return the value of exercise_record.start_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public int getStartAngle() {
        return startAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.start_angle
     *
     * @param startAngle the value for exercise_record.start_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setStartAngle(int startAngle) {
        this.startAngle = startAngle;    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.end_angle
     *
     * @return the value of exercise_record.end_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public int getEndAngle() {
        return endAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.end_angle
     *
     * @param endAngle the value for exercise_record.end_angle
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setEndAngle(int endAngle) {
        this.endAngle = endAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.sr
     *
     * @return the value of exercise_record.sr
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Integer getSr() {
        return sr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.sr
     *
     * @param sr the value for exercise_record.sr
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setSr(Integer sr) {
        this.sr = sr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_record.create_time
     *
     * @return the value of exercise_record.create_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_record.create_time
     *
     * @param createTime the value for exercise_record.create_time
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}