package com.wizinno.jas.exercise.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Report implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.ep_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Long epId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.doctor_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Long doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.start_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.end_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.verdict
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Integer verdict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.content
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.update_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.ep_id
     *
     * @return the value of report.ep_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Long getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.ep_id
     *
     * @param epId the value for report.ep_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setEpId(Long epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.doctor_id
     *
     * @return the value of report.doctor_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.doctor_id
     *
     * @param doctorId the value for report.doctor_id
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.start_time
     *
     * @return the value of report.start_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.start_time
     *
     * @param startTime the value for report.start_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.end_time
     *
     * @return the value of report.end_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.end_time
     *
     * @param endTime the value for report.end_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.verdict
     *
     * @return the value of report.verdict
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Integer getVerdict() {
        return verdict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.verdict
     *
     * @param verdict the value for report.verdict
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setVerdict(Integer verdict) {
        this.verdict = verdict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.content
     *
     * @return the value of report.content
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.content
     *
     * @param content the value for report.content
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.update_time
     *
     * @return the value of report.update_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.update_time
     *
     * @param updateTime the value for report.update_time
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}