package com.wizinno.jas.user.domain.model;

import java.io.Serializable;

public class Patient implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.user_id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.id
     *
     * @return the value of patient.id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.id
     *
     * @param id the value for patient.id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.user_id
     *
     * @return the value of patient.user_id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.user_id
     *
     * @param userId the value for patient.user_id
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}