package com.wizinno.jas.score.domain;

import com.wizinno.jas.score.domain.model.ExchangeRecord;
import com.wizinno.jas.score.service.dto.ERcouponDto;

import java.util.List;

public interface ExchangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    int insert(ExchangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    ExchangeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    List<ExchangeRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    int updateByPrimaryKey(ExchangeRecord record);

    List<ERcouponDto>getChangeRecordList(Long userId);
    List<ERcouponDto>getCouponListByUserId(Long userId);
    List<ERcouponDto>getHistoryCouponList(Long userId);
}