package com.wizinno.jas.score.domain;

import com.wizinno.jas.score.domain.model.Score;
import com.wizinno.jas.score.service.dto.ScoreDto;
import com.wizinno.jas.score.service.dto.UserScoreDto;

import java.util.List;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    Score selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    List<Score> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    int updateByPrimaryKey(Score record);

    List<Score> getScoreListByUserId(Long userId);
    List<UserScoreDto> getScoreList(UserScoreDto userScoreDto);
}