package com.wizinno.jas.device.domain.model;

import java.io.Serializable;
import java.util.Date;

public class DeviceRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.device_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.patient_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.event
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.details
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.modify_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_record.create_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.id
     *
     * @return the value of device_record.id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.id
     *
     * @param id the value for device_record.id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.device_id
     *
     * @return the value of device_record.device_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.device_id
     *
     * @param deviceId the value for device_record.device_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.patient_id
     *
     * @return the value of device_record.patient_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.patient_id
     *
     * @param patientId the value for device_record.patient_id
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.event
     *
     * @return the value of device_record.event
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.event
     *
     * @param event the value for device_record.event
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.details
     *
     * @return the value of device_record.details
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.details
     *
     * @param details the value for device_record.details
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.modify_time
     *
     * @return the value of device_record.modify_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.modify_time
     *
     * @param modifyTime the value for device_record.modify_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_record.create_time
     *
     * @return the value of device_record.create_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_record.create_time
     *
     * @param createTime the value for device_record.create_time
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}