package com.wizinno.jas.user.domain;

import com.wizinno.jas.user.domain.model.Patient;
import com.wizinno.jas.user.service.dto.UserPatientDto;

import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    Patient selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Fri Aug 11 10:45:24 CST 2017
     */
    int updateByPrimaryKey(Patient record);

    Patient getPatientByUserID(Long userId);

    UserPatientDto getPatientByPatientId(Long patientId);
}