package com.wizinno.jas.dict.domain;

import com.wizinno.jas.dict.domain.model.DataDict;
import java.util.List;

public interface DataDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    int insert(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    DataDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    List<DataDict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    int updateByPrimaryKey(DataDict record);

    String selectByKey(String key);
}