package com.wizinno.jas.score.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.id
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_password
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private String couponPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.redeem_score
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private int redeemScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_count
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private int couponCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_money
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private Double couponMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.validity
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private Date validity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.id
     *
     * @return the value of coupon.id
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.id
     *
     * @param id the value for coupon.id
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_password
     *
     * @return the value of coupon.coupon_password
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public String getCouponPassword() {
        return couponPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_password
     *
     * @param couponPassword the value for coupon.coupon_password
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public void setCouponPassword(String couponPassword) {
        this.couponPassword = couponPassword == null ? null : couponPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.redeem_score
     *
     * @return the value of coupon.redeem_score
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public int getRedeemScore() {
        return redeemScore;
    }

    public void setRedeemScore(int redeemScore) {
        this.redeemScore = redeemScore;
    }

    public int getCouponCount() {
        return couponCount;
    }

    public void setCouponCount(int couponCount) {
        this.couponCount = couponCount;
    }

    public Double getCouponMoney() {
        return couponMoney;
    }

    public void setCouponMoney(Double couponMoney) {
        this.couponMoney = couponMoney;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.validity
     *
     * @return the value of coupon.validity
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public Date getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.validity
     *
     * @param validity the value for coupon.validity
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public void setValidity(Date validity) {
        this.validity = validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.create_time
     *
     * @return the value of coupon.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.create_time
     *
     * @param createTime the value for coupon.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.update_time
     *
     * @return the value of coupon.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.update_time
     *
     * @param updateTime the value for coupon.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:41 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}