package com.wizinno.jas.score.domain.model;

import java.io.Serializable;
import java.util.Date;

public class ExchangeRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.user_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.coupon_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.status
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange_record
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.id
     *
     * @return the value of exchange_record.id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.id
     *
     * @param id the value for exchange_record.id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.user_id
     *
     * @return the value of exchange_record.user_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.user_id
     *
     * @param userId the value for exchange_record.user_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.coupon_id
     *
     * @return the value of exchange_record.coupon_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.coupon_id
     *
     * @param couponId the value for exchange_record.coupon_id
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.status
     *
     * @return the value of exchange_record.status
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.status
     *
     * @param status the value for exchange_record.status
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.create_time
     *
     * @return the value of exchange_record.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.create_time
     *
     * @param createTime the value for exchange_record.create_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.update_time
     *
     * @return the value of exchange_record.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.update_time
     *
     * @param updateTime the value for exchange_record.update_time
     *
     * @mbggenerated Fri Aug 18 14:29:02 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}