package com.wizinno.jas.score.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Score implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.user_id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score_change
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Integer scoreChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.change_value
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private String changeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.surplus_score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Long surplusScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.create_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.update_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.user_id
     *
     * @return the value of score.user_id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.user_id
     *
     * @param userId the value for score.user_id
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score_change
     *
     * @return the value of score.score_change
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Integer getScoreChange() {
        return scoreChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score_change
     *
     * @param scoreChange the value for score.score_change
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setScoreChange(Integer scoreChange) {
        this.scoreChange = scoreChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.change_value
     *
     * @return the value of score.change_value
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public String getChangeValue() {
        return changeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.change_value
     *
     * @param changeValue the value for score.change_value
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setChangeValue(String changeValue) {
        this.changeValue = changeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.surplus_score
     *
     * @return the value of score.surplus_score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Long getSurplusScore() {
        return surplusScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.surplus_score
     *
     * @param surplusScore the value for score.surplus_score
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setSurplusScore(Long surplusScore) {
        this.surplusScore = surplusScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.create_time
     *
     * @return the value of score.create_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.create_time
     *
     * @param createTime the value for score.create_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.update_time
     *
     * @return the value of score.update_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.update_time
     *
     * @param updateTime the value for score.update_time
     *
     * @mbggenerated Thu Aug 17 15:34:25 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}