package com.wizinno.jas.dict.domain.model;

import java.io.Serializable;

public class DataDict implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.id
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.key
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.sequencing
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    private Long sequencing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.content
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_dict
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.id
     *
     * @return the value of data_dict.id
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.id
     *
     * @param id the value for data_dict.id
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.key
     *
     * @return the value of data_dict.key
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.key
     *
     * @param key the value for data_dict.key
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.sequencing
     *
     * @return the value of data_dict.sequencing
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public Long getSequencing() {
        return sequencing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.sequencing
     *
     * @param sequencing the value for data_dict.sequencing
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public void setSequencing(Long sequencing) {
        this.sequencing = sequencing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.content
     *
     * @return the value of data_dict.content
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.content
     *
     * @param content the value for data_dict.content
     *
     * @mbggenerated Mon Aug 14 15:33:35 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}