package com.wizinno.jas.archival.domain.model;

import java.io.Serializable;
import java.util.Date;

public class ClinicalData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.ma_id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private Long maId;
    private int indexType;//图片类型索引
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.content
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.picture
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.type
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.create_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_data.update_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clinical_data
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.id
     *
     * @return the value of clinical_data.id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.id
     *
     * @param id the value for clinical_data.id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    public int getIndexType() {
        return indexType;
    }

    public void setIndexType(int indexType) {
        this.indexType = indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.ma_id
     *
     * @return the value of clinical_data.ma_id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public Long getMaId() {
        return maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.ma_id
     *
     * @param maId the value for clinical_data.ma_id
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setMaId(Long maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.content
     *
     * @return the value of clinical_data.content
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.content
     *
     * @param content the value for clinical_data.content
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.time
     *
     * @return the value of clinical_data.time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.time
     *
     * @param time the value for clinical_data.time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.type
     *
     * @return the value of clinical_data.type
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.type
     *
     * @param type the value for clinical_data.type
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.create_time
     *
     * @return the value of clinical_data.create_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.create_time
     *
     * @param createTime the value for clinical_data.create_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_data.update_time
     *
     * @return the value of clinical_data.update_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_data.update_time
     *
     * @param updateTime the value for clinical_data.update_time
     *
     * @mbggenerated Tue Aug 15 11:39:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}