package com.wizinno.jas.archival.domain.model;

import java.io.Serializable;
import java.util.Date;

public class MedicalArchival implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.patient_id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.surgery_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Date surgeryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.start_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.illness_state
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Integer illnessState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.activity
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Integer activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.process
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Integer process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.department
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Integer department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.hospital
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Integer hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.doctor_name
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.content
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.create_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_archival.update_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_archival
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.id
     *
     * @return the value of medical_archival.id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.id
     *
     * @param id the value for medical_archival.id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.patient_id
     *
     * @return the value of medical_archival.patient_id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.patient_id
     *
     * @param patientId the value for medical_archival.patient_id
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.surgery_time
     *
     * @return the value of medical_archival.surgery_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Date getSurgeryTime() {
        return surgeryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.surgery_time
     *
     * @param surgeryTime the value for medical_archival.surgery_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setSurgeryTime(Date surgeryTime) {
        this.surgeryTime = surgeryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.start_time
     *
     * @return the value of medical_archival.start_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.start_time
     *
     * @param startTime the value for medical_archival.start_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.illness_state
     *
     * @return the value of medical_archival.illness_state
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Integer getIllnessState() {
        return illnessState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.illness_state
     *
     * @param illnessState the value for medical_archival.illness_state
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setIllnessState(Integer illnessState) {
        this.illnessState = illnessState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.activity
     *
     * @return the value of medical_archival.activity
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Integer getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.activity
     *
     * @param activity the value for medical_archival.activity
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setActivity(Integer activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.process
     *
     * @return the value of medical_archival.process
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Integer getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.process
     *
     * @param process the value for medical_archival.process
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setProcess(Integer process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.department
     *
     * @return the value of medical_archival.department
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.department
     *
     * @param department the value for medical_archival.department
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.hospital
     *
     * @return the value of medical_archival.hospital
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Integer getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.hospital
     *
     * @param hospital the value for medical_archival.hospital
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setHospital(Integer hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.doctor_name
     *
     * @return the value of medical_archival.doctor_name
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.doctor_name
     *
     * @param doctorName the value for medical_archival.doctor_name
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.content
     *
     * @return the value of medical_archival.content
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.content
     *
     * @param content the value for medical_archival.content
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.create_time
     *
     * @return the value of medical_archival.create_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.create_time
     *
     * @param createTime the value for medical_archival.create_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_archival.update_time
     *
     * @return the value of medical_archival.update_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_archival.update_time
     *
     * @param updateTime the value for medical_archival.update_time
     *
     * @mbggenerated Tue Aug 15 13:58:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}