package com.wizinno.jas.operationLog.domain;

import com.wizinno.jas.operationLog.domain.model.OperationLog;
import com.wizinno.jas.user.service.dto.OperationLogDto;

import java.util.List;

public interface OperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);
    List<OperationLogDto> findAll(OperationLogDto operationLogDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    int insert(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    OperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    List<OperationLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbggenerated Mon Oct 23 14:38:57 CST 2017
     */
    int updateByPrimaryKey(OperationLog record);
}