package com.wizinno.jas.application.domain;

import com.wizinno.jas.application.domain.model.Application;
import com.wizinno.jas.application.service.dto.ApplicationPatientDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    int insert(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    Application selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    List<Application> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Tue Aug 15 14:21:46 CST 2017
     */
    int updateByPrimaryKey(Application record);

    List<ApplicationPatientDto> getApplications(@Param("id") Long id,@Param("filter") String filter);

    Long last();

    Application getApplicationByPIdAndDId(@Param("patientId") Long patientId, @Param("id") Long id);
}