package com.wizinno.jas.device.domain;

import com.wizinno.jas.device.domain.model.DeviceRecord;
import com.wizinno.jas.device.service.dto.DeviceRecordDto;

import java.util.List;

public interface DeviceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    int insert(DeviceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    DeviceRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    List<DeviceRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_record
     *
     * @mbggenerated Wed Oct 11 16:15:37 CST 2017
     */
    int updateByPrimaryKey(DeviceRecord record);

    List<DeviceRecordDto>getDeviceRecordListByDeviceId(Long deviceId);
}