package com.wizinno.jas.device.domain;

import com.wizinno.jas.device.domain.model.Device;
import com.wizinno.jas.device.service.dto.DeviceDto;

import java.util.List;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 26 14:16:48 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 26 14:16:48 CST 2017
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 26 14:16:48 CST 2017
     */
    Device selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 26 14:16:48 CST 2017
     */
    List<Device> selectAll();
    List<DeviceDto> selectAlls(DeviceDto deviceDto);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 26 14:16:48 CST 2017
     */
    int updateByPrimaryKey(Device record);

    Device getDeviceBySn(String sn);

    List<Device> getDevice(Long userId);

    Device getDeviceDetail(Long deviceId);

    void removeUserId(Long deviceId);
}