package com.wizinno.jas.exercise.domain;

import com.wizinno.jas.exercise.domain.model.ExerciseRecord;
import com.wizinno.jas.exercise.service.dto.ExerciseRecordDto;

import java.util.List;

public interface ExerciseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    int insert(ExerciseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    ExerciseRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    List<ExerciseRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_record
     *
     * @mbggenerated Fri Aug 18 15:13:29 CST 2017
     */
    int updateByPrimaryKey(ExerciseRecord record);

    List<ExerciseRecord> getExerciseRecord(Long id);
    ExerciseRecord getExerciseRecordById(Long id);
    List<ExerciseRecord> getExerciseRecords(ExerciseRecord dto);
    List<ExerciseRecord> getExerciseRecordTimes(ExerciseRecord dto);
    List<ExerciseRecord> Calculation(ExerciseRecord dto);
    List<ExerciseRecord> getExerciseRecordWeekMonth(ExerciseRecord dto);
    List<ExerciseRecord> getExerciseRecordDayByTime(ExerciseRecord dto);
    //查询对应康复计划下面的训练次数
    List<ExerciseRecordDto>getExerciseCount(ExerciseRecordDto exerciseRecordDto);
    //查询训练记录列表
    List<ExerciseRecordDto>findExerciseRecordList(ExerciseRecordDto exerciseRecordDto);

}