package com.wizinno.jas.exercise.domain;

import com.wizinno.jas.exercise.domain.model.ExerciseProcess;
import com.wizinno.jas.exercise.service.dto.ExerciseProcessDoctorDto;
import com.wizinno.jas.exercise.service.dto.ExerciseProcessDto;
import com.wizinno.jas.exercise.service.dto.ExerciseProcessPatientDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ExerciseProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    int insert(ExerciseProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    ExerciseProcess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    List<ExerciseProcess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_process
     *
     * @mbggenerated Thu Aug 17 13:14:19 CST 2017
     */
    int updateByPrimaryKey(ExerciseProcess record);

    List<ExerciseProcessDoctorDto> getDoctorsByPatientId(Long id);

    List<ExerciseProcessDto> getExerciseProcessByPatientId(Long patientId);

    List<ExerciseProcessPatientDto> getPatientsByPatientId(Long patientId);

    List<ExerciseProcessDto> getEPByPIdAndDId(@Param("patientId") Long patientId,@Param("id") Long id);

    List<ExerciseProcessPatientDto> getPatientByPatientId(Map map);

    List<ExerciseProcessDto>findExerciseProcessList(ExerciseProcessDto exerciseProcessDto);
}