package com.wizinno.jas.exercise.domain;

import com.wizinno.jas.exercise.domain.model.Report;
import com.wizinno.jas.exercise.service.dto.ReportDto;

import java.util.List;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    Report selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    List<Report> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated Mon Aug 21 11:36:06 CST 2017
     */
    int updateByPrimaryKey(Report record);

    List<Report> getReportByEpId(Long epId);
    List<ReportDto>findReportListByEpId(Long id);
}